version: "3.9"

volumes:
  mongodata:

services:
  mongo:
    image: mongo:3
    volumes:
      - mongodata:/data/db
    container_name: mongodb
    env_file: 
      - .env
    ports:
      - "27018:27017"
